a=int(input())
put=print
if a == 0:
    put( " * * * ")
    put( "*     *")
    put( "*     *")
    put( "*     *")
    put( "       ")
    put( "*     *")
    put( "*     *")
    put ("*     *")
    put (" * * * ")

elif a == 1:
    put ("       ")
    put ("      *")
    put ("      *")
    put ("      *")
    put ("       ")
    put ("      *")
    put ("      *")
    put ("      *")
    put ("       ")
elif a == 2:
    put (" * * * ")
    put ("      *")
    put ("      *")
    put ("      *")
    put (" * * * ")
    put ("*      ")
    put ("*      ")
    put ("*      ")
    put (" * * * ")
elif a == 3:
    put (" * * * ")
    put ("      *")
    put ("      *")
    put ("      *")
    put (" * * * ")
    put ("      *")
    put ("      *")
    put ("      *")
    put (" * * * ")
elif a == 4:
    put ("       ")
    put ("*     *")
    put ("*     *")
    put ("*     *")
    put (" * * * ")
    put ("      *")
    put ("      *")
    put ("      *")
    put ("       ")
elif a == 5:
    put (" * * * ")
    put ("*      ")
    put ("*      ")
    put ("*      ")
    put (" * * * ")
    put ("      *")
    put ("      *")
    put ("      *")
    put (" * * * ")
elif a == 6:
    put (" * * * ")
    put ("*      ")
    put ("*      ")
    put ("*      ")
    put (" * * * ")
    put ("*     *")
    put ("*     *")
    put ("*     *")
    put (" * * * ")
elif a == 7:
    put (" * * * ")
    put ("      *")
    put ("      *")
    put ("      *")
    put ("       ")
    put ("      *")
    put ("      *")
    put ("      *")
    put ("       ")
elif a == 8:
    put (" * * * ")
    put ("*     *")
    put ("*     *")
    put ("*     *")
    put (" * * * ")
    put ("*     *")
    put ("*     *")
    put ("*     *")
    put (" * * * ")
elif a == 9:
    put (" * * * ")
    put ("*     *")
    put ("*     *")
    put ("*     *")
    put (" * * * ")
    put ("      *")
    put ("      *")
    put ("      *")
    put (" * * * ")